name: C++ Compile Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Create exe directory
        run: mkdir -p exe

      - name: Compile and check
        run: bash ./compile_check.sh